Fix test workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,6 +12,12 @@ on:
     paths-ignore:
       - '**.md'
 
+env:
+  BUILD_TAG: qbittorrent:test
+  CONTAINER_NAME: qbittorrent
+  RUNNING_TIMEOUT: 120
+  RUNNING_LOG_CHECK: "WebUI will be started shortly"
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -19,14 +25,6 @@ jobs:
       -
         name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Prepare
-        id: prep
-        run: |
-          echo ::set-output name=build_tag::test
-          echo ::set-output name=container_name::qbittorrent
-          echo ::set-output name=running_timeout::120
-          echo ::set-output name=running_log_check::access the WebUI at
       -
         name: Set up QEMU
         uses: docker/setup-qemu-action@v2
@@ -39,36 +37,37 @@ jobs:
         with:
           targets: image-local
         env:
-          DEFAULT_TAG: ${{ steps.prep.outputs.build_tag }}
+          DEFAULT_TAG: ${{ env.BUILD_TAG }}
       -
         name: Start container
         run: |
-          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
-          docker run -d --name ${{ steps.prep.outputs.container_name }} ${{ steps.prep.outputs.build_tag }}
+          docker rm -f ${CONTAINER_NAME} > /dev/null 2>&1 || true
+          docker run -d --name ${CONTAINER_NAME} ${BUILD_TAG}
       -
         name: Test run
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
+          SECONDS=0
+          TIMEOUT=$((SECONDS + ${RUNNING_TIMEOUT}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
+            if [[ ${LOGLINE} == *"${RUNNING_LOG_CHECK}"* ]]; then
               echo "🎉 Container up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.container_name }} container"
+              >&2 echo "❌ Failed to run ${CONTAINER_NAME} container"
               exit 1
             fi
-          done < <(docker logs -f ${{ steps.prep.outputs.container_name }} 2>&1)
+          done < <(docker logs -f ${CONTAINER_NAME} 2>&1)
 
-          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prep.outputs.container_name }})
+          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${CONTAINER_NAME})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
-            >&2 echo "❌ Container ${{ steps.prep.outputs.container_name }} returned status '$CONTAINER_STATUS'"
+            >&2 echo "❌ Container ${CONTAINER_NAME} returned status '$CONTAINER_STATUS'"
             exit 1
           fi
       -
-        name: Container logs
+        name: Logs
         if: always()
         run: |
-          docker logs ${{ steps.prep.outputs.container_name }}
-          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
+          docker logs ${CONTAINER_NAME}
+          docker rm -f ${CONTAINER_NAME} > /dev/null 2>&1 || true
